// This model was generated by Lumber. However, you remain in control of your models.
// Learn how here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models

module.exports = (mongoose, Mongoose) => {
   // This section contains the properties of your model, mapped to your collection's properties.
   // Learn more here: https://docs.forestadmin.com/documentation/v/v6/reference-guide/models/enrich-your-models#declaring-a-new-field-in-a-model
   const schema = Mongoose.Schema(
      {
         email: String,
         createdAt: Date,
         updatedAt: Date,
         token: String,
         salt: String,
         hash: String,
         account: {
            userName: String,
            languageDefault: String,
            tutorialSeen: Boolean,
            secretCode: Number,
            isActif: Boolean,
            isAdmin: Boolean,
         },
      },
      {
         timestamps: false,
      }
   );

   return mongoose.model("users", schema, "users");
};
